#!/bin/zsh

alias rs='rails server'
alias rsd='rails server --debugger'
alias rsp='rails server -e production'
alias rst='rails server -e test'
alias rc='rails console'
alias rcd='rails console --debugger'
alias rcp='rails console production'
alias rct='rails console test'
alias rg='rails generate'
alias rd='rails destroy'
alias rp='rails plugin'

alias bers='bundle exec rails server'
alias bersd='bundle exec rails server --debugger'
alias bersp='bundle exec rails server -e production'
alias berst='bundle exec rails server -e test'
alias berc='bundle exec rails console'
alias bercd='bundle exec rails console --debugger'
alias bercp='bundle exec rails console production'
alias berct='bundle exec rails console test'
alias berg='bundle exec rails generate'
alias berd='bundle exec rails destroy'
alias berp='bundle exec rails plugin'